# Generated by Django 3.1.3 on 2020-11-14 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_tweets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='client_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.client_tag'),
        ),
    ]
